### ISSUE TITLE
Youtube videos won't play. Problem with 'inject_into_urllib3'

### ISSUE THREAD

**Issue by mvineetmenon** [jdf76/plugin.video.youtube#109]
Apologies if this has been reported before, but Youtube doesn't seem to work on my Kodi.

I have kodi 17 running on a raspbian jessie. PyOpenSSL is v0.13. 

Relevant error log is as follows,

```
12:19:11.625 T:2572260272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'inject_into_urllib3'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/startup.py", line 3, in <module>
                                                from youtube_plugin.kodion.impl import Context
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
                                                from requests import api as client
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
                                                pyopenssl.inject_into_urllib3()
                                            AttributeError: 'module' object has no attribute 'inject_into_urllib3'
                                            -->End of Python script error report<--

```

**Comment by anxdpanic** [comment]
v0.13 is from 2013 by the looks of it, would start by upgrading that.
sudo pip install pyopenssl --upgrade

**Comment by anxdpanic** [comment]
closing due to inactivity
