### ISSUE TITLE
Crash with `AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_X25519`

### ISSUE THREAD

**Issue by dankeder** [jdf76/plugin.video.youtube#112]
The plugin is crashing on my system with the following error message:

```
09:48:35.084 T:140258210629376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.AttributeError'>
    Error Contents: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_X25519'
    Traceback (most recent call last):
      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 3, in <module>
        from youtube_plugin.kodion import runner
      File "/home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
        from requests import api as client
      File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 52, in <module>
        from .packages.urllib3.contrib import pyopenssl
      File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
        import OpenSSL.SSL
      File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
        from OpenSSL._util import (
      File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
        from cryptography.hazmat.bindings.openssl.binding import Binding
      File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
        Binding.init_static_locks()
      File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
        cls._ensure_ffi_initialized()
      File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
        cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
      File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 84, in build_conditional_library
        if not getattr(lib, condition):
    AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_X25519'
    -->End of Python script error report<--
```

The OS is Fedora 26. These packages are installed there:

- openssl-1.1.0f-7.fc26.x86_64
- python2-cryptography-2.0.2-1.fc26.x86_64

**Comment by dankeder** [comment]
Please let me know if more details is needed, I'll update the issue. And thanks for the great plugin!

**Comment by anxdpanic** [comment]
I'm not proficient with the underlying dependency quirks that linux brings. That being said, it seems like there has been some bugs between pyopenssl/cryptography. I am also not sure for linux which and when system vs python packages are used in Kodi's case.
Most common solutions I've seen to the similar issues is down/upgrading/removing the python packages, so I would start there. 

sudo pip install pyopenssl --upgrade
sudo pip install cryptography --upgrade

**Comment by dankeder** [comment]
All right, I tried it with a new Kodi profile and it worked flawlessly. It seems it was a problem on my end only.
