### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by fernandog** [jdf76/plugin.video.youtube#114]
Got this in my logs with Kodi 17 :

version="5.4.2"

```
19:36:01.305 T:1959006208  NOTICE: Starting Kodi (17.3). Platform: Linux ARM (Thumb) 32-bit
19:36:01.305 T:1959006208  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
19:36:01.305 T:1959006208  NOTICE: Kodi compiled Jul 29 2017 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.39 (200743)
```

```
19:36:11.087 T:1637872624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: bad marshal data (unknown type code)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/startup.py", line 3, in <module>
                                                from youtube_plugin.kodion.impl import Context
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
                                                from requests import api as client
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 52, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/__init__.py", line 27, in <module>
                                                from . import urllib3
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/__init__.py", line 8, in <module>
                                                from .connectionpool import (
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 11, in <module>
                                                from .exceptions import (
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/exceptions.py", line 2, in <module>
                                                from .packages.six.moves.http_client import (
                                            ValueError: bad marshal data (unknown type code)
                                            -->End of Python script error report<--
```

**Comment by fernandog** [comment]
deleted all .pyc files and rebooted. no more issue
