### ISSUE TITLE
Error YouTube (kodi running on iPad 3.5 32 bit jailbreaked )

### ISSUE THREAD

**Issue by pplanteg** [jdf76/plugin.video.youtube#186]
Hello 

First thank's for you're job done here.

I have an error upon installing YouTube plugging on my iPad running kodi.
As soon as the plugin is installed and when I try to open the plugin I have a message saying "YouTube error" check kodi log...

Here a part of that log :

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (10, 'No child processes')
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/startup.py", line 3, in <module>
                                                from youtube_plugin.kodion.impl import Context
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
                                                from requests import api as client
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/__init__.py", line 97, in <module>
                                                from . import utils
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/utils.py", line 42, in <module>
                                                if platform.system() == 'Windows':
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 1263, in system
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 1230, in uname
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 965, in _syscmd_uname
                                            IOError: (10, 'No child processes')
                                            -->End of Python script error report<--
08:46:37.375 T:1074876416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (10, 'No child processes')
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/default.py", line 3, in <module>
                                                from youtube_plugin.kodion import runner
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/__init__.py", line 17, in <module>
                                                from requests import api as client
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/__init__.py", line 97, in <module>
                                                from . import utils
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/utils.py", line 42, in <module>
                                                if platform.system() == 'Windows':
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 1263, in system
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 1230, in uname
                                              File "/Users/Shared/jenkins/workspace/IOS/tools/depends/xbmc-depends/iphoneos8.1_armv7-target/lib/python2.7/platform.py", line 965, in _syscmd_uname
                                            IOError: (10, 'No child processes')
                                            -->End of Python script error report<--
08:46:37.400 T:1076473856   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
08:46:37.401 T:1076473856   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
08:46:42.400 T:1080201216 WARNING: DARWINIOS: underflow (0 vs 8192 bytes)

just to let you know that, thank you have a nice day.

Philippe

**Comment by MohammedHoosen** [comment]
Try clearing your plugin cache.

**Comment by pplanteg** [comment]
Hi, thank's but already tried, more than that I've completely uninstalled kodi and deleted the kodi folder in library with ifile but same problem on reinstall

**Comment by pplanteg** [comment]
Update... It's not YouTube plugin problem ! It my version of kodi for iPad ... I've tried an old version and everything goes well with YouTube install 
For your infos I was using kodi 17.5 install from .deb (32bit) version ... I've tried on kodi 15.4 and everything's ok now 

Anyway thank you ... Have a nice day

**Comment by anxdpanic** [comment]
Thank you for the heads up, I don't any iOS devices to test with. I did run into an error when the new script.module.requests updated about the same time as this issue. It simply required a reboot though to reinit the module.
