### ISSUE TITLE
URLErrors when trying to do anything.

### ISSUE THREAD

**Issue by gyates100895** [jdf76/plugin.video.youtube#23]
I recently did a fresh install of my OS (Ubuntu-Gnome 16.10) and freshly installed kodi v17. Upon installing this addon, inputting in my personal YouTube API values, and trying to search, I noticed errors in the kodi.log file. The following is the excerpt:
`17:35:04.321 T:140641075738368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 0] Error>
                                            Traceback (most recent call last):
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 93, in navigate
                                                result = method(context, re_match)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 225, in _internal_search
                                                return self.on_search(query, context, re_match)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 481, in on_search
                                                page_token=page_token)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/function_cache.py", line 107, in get
                                                cached_data = partial_func()
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 488, in search
                                                return self._perform_v3_request(method='GET', path='search', params=params, quota_optimized=False)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/youtube/client/youtube.py", line 615, in _perform_v3_request
                                                result = requests.get(_url, params=_params, headers=_headers, verify=False, allow_redirects=allow_redirects)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 189, in get
                                                return _request('GET', url, **kwargs)
                                              File "/home/greg/.kodi/addons/plugin.video.youtube/resources/lib/kodion/simple_requests/api.py", line 165, in _request
                                                response = opener.open(request)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 0] Error>
                                            -->End of Python script error report<--`

I have searched around for this problem and found one conclusion that works. In the file `resources/lib/kodion/simple_requests/api.py` the very first import should be for OpenSSL. thus the line would be literally `import OpenSSL`
Upon adding this line in the beginning of the file, everything began working as it should.

**Comment by anxdpanic** [comment]
please see #14
