### ISSUE TITLE
Exception when trying to watch a youtube live stream: unknown yt_format for itag "300"

### ISSUE THREAD

**Issue by cmsimike** [jdf76/plugin.video.youtube#233]
Hi,

Today I went to load up a live youtube stream and got

<pre>
16:24:55.891 T:140372516243200   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: unknown yt_format for itag "300"
                                            Traceback (most recent call last):
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 40, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 93, in navigate
                                                result = method(context, re_match)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 377, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 19, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 80, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 353, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 661, in _method_get_video_info
                                                return self._method_watch(video_id, html, reason=params.get('reason', 'UNKNOWN'), meta_info=meta_info)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 458, in _method_watch
                                                return self._load_manifest(player_args.get('hlsvp'), video_id, meta_info=meta_info)
                                              File "/home/mike/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 567, in _load_manifest
                                                raise Exception('unknown yt_format for itag "%s"' % itag)
                                            Exception: unknown yt_format for itag "300"
                                            -->End of Python script error report<--
16:24:55.956 T:140377110706560   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=hjS1dz0Rozk]
</pre>

**Comment by anxdpanic** [comment]
fixed with a302932e4a5860fe715a74698a1b181dd7d012e1
will be included in the next alpha bump

**Comment by cmsimike** [comment]
@anxdpanic Thank you very much! I will close this out.
