### ISSUE TITLE
[5.5.0~alpha15] Invalid parameters when playing streams which are not meant to play as embedded

### ISSUE THREAD

**Issue by Twilight0** [jdf76/plugin.video.youtube#234]
This is actually a live stream, It may apply to on demand as well, I am not sure.

Greece geolocked: https://www.youtube.com/embed/0XYWTzFlEyo

Worldwide: https://www.youtube.com/embed/Zx98moCvkpU

I tried utilizing youtube_requests.py's resolver and I am getting an exception.
I tried calling youtube addon directly via plugin://plugin.video.youtube/?video_id=0XYWTzFlEyo and its failing miserably.

**Comment by anxdpanic** [comment]
@Twilight0 can you try latest master and let me know if you're getting the expected results. The worldwide is now working for me.

**Comment by Twilight0** [comment]
youtube_requests.py is throwing an error:

23:02:59.707 T:5508   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'youtube_plugin.youtube.youtube_exceptions.YouTubeException'>
                                            Traceback (most recent call last):
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.AliveGR\runner.py", line 237, in <module>
                                                player(url, name)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.AliveGR\resources\lib\modules\player.py", line 386, in player
                                                stream = router(link)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.AliveGR\resources\lib\modules\player.py", line 257, in router
                                                stream = youtu.wrapper(link)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.AliveGR\resources\lib\resolvers\youtu.py", line 54, in wrapper
                                                streams = youtube_resolver.resolve(url)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_resolver.py", line 105, in resolve
                                                streams = client.get_video_streams(context=context, video_id=v_id.group('video_id'))
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\youtube.py", line 79, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 403, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 636, in _method_get_video_info
                                                raise YouTubeException(reason)
                                            YouTubeException: \xce\xa4\xce\xbf \xce\xb2\xce\xaf\xce\xbd\xcf\x84\xce\xb5\xce\xbf \xce\xb1\xcf\x85\xcf\x84\xcf\x8c \xcf\x80\xce\xb5\xcf\x81\xce\xb9\xce\xbb\xce\xb1\xce\xbc\xce\xb2\xce\xac\xce\xbd\xce\xb5\xce\xb9 \xcf\x80\xce\xb5\xcf\x81\xce\xb9\xce\xb5\xcf\x87\xcf\x8c\xce\xbc\xce\xb5\xce\xbd\xce\xbf \xce\xb1\xcf\x80\xcf\x8c \xcf\x84\xce\xbf\xce\xbd \xcf\x83\xcf\x85\xce\xbd\xce\xb5\xcf\x81\xce\xb3\xce\xac\xcf\x84\xce\xb7 ERT - Digital Minds, \xce\xbf \xce\xbf\xcf\x80\xce\xbf\xce\xaf\xce\xbf\xcf\x82 \xce\xad\xcf\x87\xce\xb5\xce\xb9 \xce\xb1\xcf\x80\xce\xbf\xce\xba\xce\xbb\xce\xb5\xce\xaf\xcf\x83\xce\xb5\xce\xb9 \xcf\x84\xce\xb7\xce\xbd \xce\xb5\xce\xbc\xcf\x86\xce\xac\xce\xbd\xce\xb9\xcf\x83\xce\xae \xcf\x84\xce\xbf\xcf\x85 \xcf\x83\xce\xb5 \xce\xb1\xcf\x85\xcf\x84\xcf\x8c\xce\xbd \xcf\x84\xce\xbf\xce\xbd \xce\xb9\xcf\x83\xcf\x84\xcf\x8c\xcf\x84\xce\xbf\xcf\x80\xce\xbf \xce\xae \xcf\x84\xce\xb7\xce\xbd \xce\xb5\xcf\x86\xce\xb1\xcf\x81\xce\xbc\xce\xbf\xce\xb3\xce\xae.
                                            <a href='http://www.youtube.com/watch?v=0XYWTzFlEyo&feature=player_embedded' target='_blank'>\xce\xa0\xce\xb1\xcf\x81\xce\xb1\xce\xba\xce\xbf\xce\xbb\xce\xbf\xcf\x85\xce\xb8\xce\xae\xcf\x83\xcf\x84\xce\xb5 \xcf\x83\xcf\x84\xce\xbf YouTube</a>
                                            -->End of Python script error report<--

I am not passing the video id only, I am passing the https://www.youtube.com/watch?v={0}.format(id)

I 'll try passing id only.

**Comment by Twilight0** [comment]
I can confirm the latest [https://github.com/jdf76/plugin.video.youtube/pull/238](url) resolves it.

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/releases
