### ISSUE TITLE
Can't play a playlist

### ISSUE THREAD

**Issue by devhell** [jdf76/plugin.video.youtube#4]
Hi,

A playlist of mine cannot be played anymore (but it has been previously). Please see below for log info. If I'm missing something, please let me know. Thank you!

```
18:53:56 7121.544434 T:1758663664  NOTICE: [plugin.video.youtube] Running: YouTube (5.3.6) on Jarvis (16.1) with Python 2.7.9
18:54:41 7166.189453 T:1434448880  NOTICE: Previous line repeats 1 times.
18:54:41 7166.189941 T:1434448880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'publishedAt'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 93, in navigate
                                                result = method(context, re_match)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 369, in on_play
                                                return yt_play.play_playlist(self, context, re_match)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_play.py", line 110, in play_playlist
                                                progress_dialog = _load_videos()
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_play.py", line 79, in _load_videos
                                                _load_videos(_page_token=next_page_token, _progress_dialog=_progress_dialog)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_play.py", line 71, in _load_videos
                                                result = v3.response_to_items(provider, context, json_data, process_next_page=False)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/v3.py", line 213, in response_to_items
                                                result.extend(_process_list_response(provider, context, json_data))
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/v3.py", line 198, in _process_list_response
                                                utils.update_video_infos(provider, context, video_id_dict, playlist_item_id_dict, channel_items_dict)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/utils.py", line 218, in update_video_infos
                                                datetime = utils.datetime_parser.parse(snippet['publishedAt'])
                                            KeyError: 'publishedAt'
                                            -->End of Python script error report<--
18:55:01 7186.316895 T:1434448880  NOTICE: [plugin.video.youtube] Running: YouTube (5.3.6) on Jarvis (16.1) with Python 2.7.9
18:55:18 7203.445312 T:1956271024  NOTICE: Previous line repeats 2 times.
18:55:18 7203.445312 T:1956271024   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/config/youtube/
18:55:18 7203.448242 T:1956271024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/config/youtube/) failed
```

**Comment by anxdpanic** [comment]
Are you able to confirm if this is still an issue in 5.3.10

**Comment by devhell** [comment]
Seems to work now! Thanks a million! :)
