### ISSUE TITLE
Error in some movies (kodi.log)

### ISSUE THREAD

**Issue by drrak** [jdf76/plugin.video.youtube#471]
Error in some movies. e.g. this: https://youtu.be/2_B4WPnf-AY
kodi.log
```
13:11:06.158 T:1728050080 WARNING: CSkinInfo: failed to load skin settings
13:11:14.834 T:1738535840   ERROR: GetDirectory - Error getting
13:11:15.684 T:1711272864   ERROR: Previous line repeats 6 times.
13:11:15.684 T:1711272864  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.0) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /kodion/search/query/
                                            	Params: {'q': 'dune dos'}
13:11:22.116 T:1711272864  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.0) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': '2_B4WPnf-AY'}
13:11:24.868 T:1711272864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Signature function not found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 52, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 87, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 11, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 631, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 28, in play_video
                                                video_streams = client.get_video_streams(context, video_id, embeddable=embeddable)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 84, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies, embeddable)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 416, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies, embeddable)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 743, in _method_get_video_info
                                                params.get('length_seconds', '0'), cipher)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 920, in generate_mpd
                                                url = ''.join([url, '&signature=', cipher.get_signature(stream_map['s'])])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 24, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 102, in get
                                                cached_data = partial_func()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 47, in _load_json_script
                                                return self._load_javascript(javascript)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_javascript
                                                raise Exception('Signature function not found')
                                            Exception: Signature function not found
                                            -->End of Python script error report<--
13:11:25.024 T:1945018480   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=2_B4WPnf-AY]
```
_RPi3, LibreELEC 8.2.5, YT 6.2.0_

**Comment by anxdpanic** [comment]
Just posted a fix, update to 6.2.2 here https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.2
