### ISSUE TITLE
6.2.3~beta1 ERROR (kodi.log)

### ISSUE THREAD

**Issue by drrak** [jdf76/plugin.video.youtube#477]
_RPi3, LibreELEC 8.2.5, YT 6.2.3~beta1_

Kodi.log
```
10:28:34.306 T:1439687584  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.3~beta1) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'H3T6JXVHaCc'}
10:28:35.561 T:1439687584   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'title'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 52, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 87, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 11, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 633, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 33, in play_video
                                                video_streams = client.get_video_streams(context, video_id, embeddable=embeddable)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 88, in get_video_streams
                                                title = '%s (%s)' % (context.get_ui().bold(video_stream['title']), video_stream['container'])
                                            KeyError: 'title'
                                            -->End of Python script error report<--
10:28:35.723 T:1944797296   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=H3T6JXVHaCc]
```

**Comment by anxdpanic** [comment]
thanks, will be fixed in the next bump, should be very few videos it occurs on (mainly from My Channel)

**Comment by anxdpanic** [comment]
fixed : https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.3-dev
