### ISSUE TITLE
Enable plugin to be used in widgets

### ISSUE THREAD

**Issue by dbalzan** [jdf76/plugin.video.youtube#51]
The Kodi 17 Estuary skin and Estuary mod makes it easy to configure YouTube widgets on the home menu.  When you have more than one widget the plugin sometimes errors with a "database is locked error".  On slower devices this happens all the time.  It would be great if the plugin could be enhanced to allow concurrent database access without failing.  Thanks.

**Example Home Page Menu**
![2017-04-15 08_47_42-clipboard](https://cloud.githubusercontent.com/assets/13656798/25062029/5d9b571c-21bb-11e7-948e-9b41b12cc671.png)

**Example Error**
`07:21:35.933 T:3567252384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: database is locked
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/abstract_provider.py", line 93, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/provider.py", line 397, in _on_yt_specials
                                                return yt_specials.process(category, self, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_specials.py", line 246, in process
                                                return _process_popular_right_now(provider, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/yt_specials.py", line 47, in _process_popular_right_now
                                                result.extend(v3.response_to_items(provider, context, json_data))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/v3.py", line 213, in response_to_items
                                                result.extend(_process_list_response(provider, context, json_data))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/v3.py", line 198, in _process_list_response
                                                utils.update_video_infos(provider, context, video_id_dict, playlist_item_id_dict, channel_items_dict)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/utils.py", line 164, in update_video_infos
                                                video_data = resource_manager.get_videos(video_ids)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/resource_manager.py", line 109, in get_videos
                                                result.update(self._update_videos(list_of_50))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube/helper/resource_manager.py", line 81, in _update_videos
                                                video_ids_to_update)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/function_cache.py", line 108, in get
                                                self._set(cache_id, cached_data)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/storage.py", line 134, in _set
                                                self._execute(True, query, values=[item_id, now, _encode(item)])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/kodion/utils/storage.py", line 79, in _execute
                                                return self._cursor.execute(query, values)
                                            OperationalError: database is locked
                                            -->End of Python script error report<--`

**Comment by anxdpanic** [comment]
I've increased the sqlite timeout in https://github.com/jdf76/plugin.video.youtube/pull/58/commits/96a17caf69c9be7321b495b5ddfebc70d3185ce8 if you want to give the current master a try.

**Comment by dbalzan** [comment]
Thanks but same issue still occurs

`17:15:28.679 T:13000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: database is locked
                                            Traceback (most recent call last):
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\runner.py", line 32, in run
                                                __RUNNER__.run(provider, context)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 93, in navigate
                                                result = method(context, re_match)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\register_provider_path.py", line 12, in wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 397, in _on_yt_specials
                                                return yt_specials.process(category, self, context, re_match)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_specials.py", line 252, in process
                                                return _process_new_uploaded_videos_tv(provider, context, re_match)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_specials.py", line 230, in _process_new_uploaded_videos_tv
                                                result.extend(tv.my_subscriptions_to_items(provider, context, json_data))
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\tv.py", line 23, in my_subscriptions_to_items
                                                utils.update_video_infos(provider, context, video_id_dict, channel_items_dict=channel_item_dict)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\utils.py", line 164, in update_video_infos
                                                video_data = resource_manager.get_videos(video_ids)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\resource_manager.py", line 109, in get_videos
                                                result.update(self._update_videos(list_of_50))
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\resource_manager.py", line 81, in _update_videos
                                                video_ids_to_update)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\function_cache.py", line 108, in get
                                                self._set(cache_id, cached_data)
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\storage.py", line 135, in _set
                                                self._execute(True, query, values=[item_id, now, _encode(item)])
                                              File "C:\Users\David Balzan\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\storage.py", line 80, in _execute
                                                return self._cursor.execute(query, values)
                                            OperationalError: database is locked
                                            -->End of Python script error report<--`

**Comment by anxdpanic** [comment]
Can you try 5.4.0 alpha3.zip or greater from the release tag below. Resolved issues with widgets in my windows environment
https://github.com/jdf76/plugin.video.youtube/releases/tag/5.4.0

Thanks

**Comment by dbalzan** [comment]
Yes that's fixed it.  Thanks.

**Comment by anxdpanic** [comment]
Thank you for testing and confirming.
