### ISSUE TITLE
Playing video failed - SSLError CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by honyczek** [jdf76/plugin.video.youtube#545]
Hello,

today some videos played, but mostly not. In Kodi.log is ERROR:
```
16:39:43.312 T:1748886432  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.3) on Krypton (Kodi-17.6) with Python 2.7.13
                                                Path: /
                                                Params: {'action': 'play_video', 'videoid': 'uT3SBzmDxGk'}
16:39:43.343 T:1748886432 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=uT3SBzmDxGk"
16:39:43.343 T:1748886432 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=uT3SBzmDxGk"
16:39:43.871 T:1748886432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /embed/uT3SBzmDxGk?gl=CZ&hl=cs (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 52, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 23, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 87, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 118, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1266, in on_root
                                                return yt_old_actions.process_old_action(self, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_old_actions.py", line 53, in process_old_action
                                                return _process_play_video(provider, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_old_actions.py", line 19, in _process_play_video
                                                return provider.on_play(new_context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 11, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 633, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 33, in play_video
                                                video_streams = client.get_video_streams(context, video_id, embeddable=embeddable)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 84, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies, embeddable)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 486, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies, embeddable)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 659, in _method_get_video_info
                                                page_result = self.get_embed_page(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 528, in get_embed_page
                                                result = requests.get(url, params=params, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 72, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 58, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 512, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 622, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 511, in send
                                                raise SSLError(e, request=request)
                                            SSLError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /embed/uT3SBzmDxGk?gl=CZ&hl=cs (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
                                            -->End of Python script error report<--
16:39:44.020 T:1945514560   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/?action=play_video&videoid=uT3SBzmDxGk]

```

**Comment by honyczek** [comment]
Thank you. I've updated plugin.video.youtube to 6.3.1 (6.3.0-dev is not accessible for me), but it's still the same error. May be it's kodi's error with certificates.
