### ISSUE TITLE
Videos failed to play again

### ISSUE THREAD

**Issue by XxAcielxX** [jdf76/plugin.video.youtube#627]
Hello,
Again from 2 days a lot of videos are not playing. I'm using 4.5.0 beta 1, did `Clear Function Cache` as well.

Example Video:
https://youtu.be/k1aHcAewT-s

Debug Log:

```
> 2019-06-22 12:17:22.277 T:4064928640   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
> 2019-06-22 12:17:22.293 T:4064928640   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
> 2019-06-22 12:17:22.293 T:4064928640   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
> 2019-06-22 12:17:22.293 T:3800019840   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Playlist.OnClear  - data: {"playlistid":1}
> 2019-06-22 12:17:22.294 T:3800019840   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"type":"unknown"},"playlistid":1,"position":0}
> 2019-06-22 12:17:22.294 T:4064941376   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/play/','2','?video_id=k1aHcAewT-s','resume:false')
> 2019-06-22 12:17:22.295 T:3591631744   DEBUG: Thread LanguageInvoker start, auto delete: false
> 2019-06-22 12:17:22.295 T:3591631744    INFO: initializing python engine.
> 2019-06-22 12:17:22.295 T:3591631744   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
> 2019-06-22 12:17:22.315 T:3690914688   DEBUG: Thread scriptobs start, auto delete: false
> 2019-06-22 12:17:22.322 T:3791627136   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnClear  - data: {"playlistid":1}
> 2019-06-22 12:17:22.323 T:3791627136   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"type":"unknown"},"playlistid":1,"position":0}
> 2019-06-22 12:17:22.326 T:3591631744   DEBUG: -->Python Interpreter Initialized<--
> 2019-06-22 12:17:22.327 T:3591631744   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py"
> 2019-06-22 12:17:22.329 T:3591631744   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.youtube/resources/lib:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.kodi-six/libs:/storage/.kodi/addons/script.module.requests/lib:/storage/.kodi/addons/script.module.six/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
> 2019-06-22 12:17:22.329 T:3591631744   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /storage/.kodi/addons/plugin.video.youtube/resources/lib
> 2019-06-22 12:17:22.329 T:3591631744   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.20.0 of the xbmc.python api
> 2019-06-22 12:17:22.516 T:4064941376   DEBUG: ------ Window Init (DialogBusy.xml) ------
> 2019-06-22 12:17:23.110 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:23.110 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:23.113 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:23.114 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:23.114 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:23.115 T:3591631744   DEBUG: [plugin.video.youtube] send_notification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": true, "whitelist": "", "httpd_port": 50152}|
> 2019-06-22 12:17:23.116 T:3591631744   DEBUG: [plugin.video.youtube] JSONStore Load |/storage/.kodi/userdata/addon_data/plugin.video.youtube/api_keys.json|
> 2019-06-22 12:17:23.117 T:3591631744   DEBUG: [plugin.video.youtube] JSONStore Load |/storage/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
> 2019-06-22 12:17:23.122 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:23.122 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:23.125 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:23.126 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:23.126 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:23.131 T:4064928640   DEBUG: CAnnouncementManager - Announcement: check_settings from plugin.video.youtube
> 2019-06-22 12:17:23.131 T:4064928640   DEBUG: GOT ANNOUNCEMENT, type: 512, from plugin.video.youtube, message check_settings
> 2019-06-22 12:17:23.145 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:23.145 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:23.147 T:3808412544   DEBUG: [plugin.video.youtube] onNotification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": true, "whitelist": "", "httpd_port": 50152}|
> 2019-06-22 12:17:23.148 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:23.149 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:23.149 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:23.157 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:23.157 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:23.160 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:23.161 T:3791627136   DEBUG: Skin Helper Service --> Kodi_Monitor: sender plugin.video.youtube - method: Other.check_settings  - data: ["%7B%22httpd_address%22%3A%20%220.0.0.0%22%2C%20%22use_httpd%22%3A%20true%2C%20%22whitelist%22%3A%20%22%22%2C%20%22httpd_port%22%3A%2050152%7D"]
> 2019-06-22 12:17:23.161 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:23.161 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:23.166 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:23.166 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:23.169 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:23.170 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:23.170 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:23.172 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.access_token) was not found.
> 2019-06-22 12:17:23.172 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.refresh_token) was not found.
> 2019-06-22 12:17:23.172 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.access_token.expires) was not found.
> 2019-06-22 12:17:23.172 T:3591631744   DEBUG: CSettingsManager: requested setting (youtube.api.last.hash) was not found.
> 2019-06-22 12:17:23.172 T:3591631744   DEBUG: [plugin.video.youtube] User: |0| Using API key set: |1|
> 2019-06-22 12:17:23.174 T:3800019840   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender plugin.video.youtube - method: Other.check_settings  - data: ["%7B%22httpd_address%22%3A%20%220.0.0.0%22%2C%20%22use_httpd%22%3A%20true%2C%20%22whitelist%22%3A%20%22%22%2C%20%22httpd_port%22%3A%2050152%7D"]
> 2019-06-22 12:17:23.183 T:3591631744   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
> 2019-06-22 12:17:23.183 T:3591631744  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.0~beta1) on Leia (Kodi-18.2) with Python 2.7.16
>                                             	Path: /play/
>                                             	Params: {'video_id': 'k1aHcAewT-s'}
> 2019-06-22 12:17:23.185 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:23.185 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:23.188 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:23.189 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:23.189 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:23.202 T:3591631744   DEBUG: [plugin.video.youtube] JSONStore Load |/storage/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
> 2019-06-22 12:17:23.203 T:3591631744   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
> 2019-06-22 12:17:23.204 T:3591631744   DEBUG: [plugin.video.youtube] Access token count: |2| Refresh token count: |2|
> 2019-06-22 12:17:23.206 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:23.206 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:23.209 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:23.210 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:23.210 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:23.211 T:3591631744   DEBUG: [plugin.video.youtube] User is logged in
> 2019-06-22 12:17:26.011 T:3591631744   DEBUG: [plugin.video.youtube] Subtitle get_subtitles: for setting |0|
> 2019-06-22 12:17:26.016 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:26.016 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:26.022 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:26.025 T:3591631744   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:26.025 T:3591631744   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:26.045 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:26.046 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:26.051 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:26.055 T:3635716992   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:26.055 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:26.061 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:26.061 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:26.067 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:26.070 T:3635716992   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:26.070 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:26.071 T:3635716992   DEBUG: [plugin.video.youtube] HTTPServer: Request uri path |/ping|
> 2019-06-22 12:17:26.071 T:3635716992   DEBUG: [plugin.video.youtube] HTTPServer: Connection from |127.0.0.1| Local range: |True|
> 2019-06-22 12:17:26.076 T:3591631744   DEBUG: [plugin.video.youtube] HTTPServer: Ping |127.0.0.1:50152| |204|
> 2019-06-22 12:17:26.079 T:3591631744   DEBUG: [plugin.video.youtube] Player JavaScript: |https://www.youtube.com/yts/jsbin/player_ias-vfl49f_g4/en_US/base.js|
> 2019-06-22 12:17:27.394 T:3591631744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.Exception'>
>                                             Error Contents: Signature function not found
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
>                                                 runner.run(__provider__)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
>                                                 __RUNNER__.run(provider, context)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 32, in run
>                                                 results = provider.navigate(context)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 117, in navigate
>                                                 result = method(context, re_match)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
>                                                 return func(*args, **kwargs)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 722, in on_play
>                                                 return yt_play.play_video(self, context)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 47, in play_video
>                                                 video_streams = client.get_video_streams(context, video_id)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
>                                                 video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
>                                                 return self._method_get_video_info(video_id, player_config, cookies)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 898, in _method_get_video_info
>                                                 cipher)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1187, in generate_mpd
>                                                 url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
>                                                 json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 113, in get
>                                                 cached_data = partial_func()
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _load_json_script
>                                                 return self._load_javascript(javascript)
>                                               File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 60, in _load_javascript
>                                                 raise Exception('Signature function not found')
>                                             Exception: Signature function not found
>                                             -->End of Python script error report<--
> 2019-06-22 12:17:27.394 T:3591631744   DEBUG: onExecutionDone(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py)
> 2019-06-22 12:17:27.398 T:4064941376   DEBUG: ------ Window Init (DialogNotification.xml) ------
> 2019-06-22 12:17:27.515 T:3591631744    INFO: Python interpreter stopped
> 2019-06-22 12:17:27.516 T:3591631744   DEBUG: Thread LanguageInvoker 3591631744 terminating
> 2019-06-22 12:17:27.521 T:3690914688   DEBUG: Thread scriptobs 3690914688 terminating
> 2019-06-22 12:17:27.530 T:4064941376   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
> 2019-06-22 12:17:27.530 T:4064941376   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=k1aHcAewT-s]
> 2019-06-22 12:17:27.530 T:4064941376   DEBUG: Playlist Player: one or more items failed to play... aborting playback
> 2019-06-22 12:17:27.530 T:4064941376   DEBUG: ------ Window Init (DialogConfirm.xml) ------
> 2019-06-22 12:17:27.530 T:4064941376    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
> 2019-06-22 12:17:32.392 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:32.396 T:3716092800   DEBUG: JSONRPC Server: New connection detected
> 2019-06-22 12:17:32.396 T:3716092800    INFO: JSONRPC Server: New connection added
> 2019-06-22 12:17:32.399 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:33.177 T:4064941376   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
> 2019-06-22 12:17:33.824 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:33.830 T:4064941376   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
> 2019-06-22 12:17:33.964 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:34.007 T:4064941376   DEBUG: Previous line repeats 1 times.
> 2019-06-22 12:17:34.007 T:4064941376   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
> 2019-06-22 12:17:34.030 T:4064928640   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
> 2019-06-22 12:17:34.030 T:4064928640   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
> 2019-06-22 12:17:34.031 T:3791627136   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnClear  - data: {"playlistid":1}
> 2019-06-22 12:17:34.076 T:3800019840   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Playlist.OnClear  - data: {"playlistid":1}
> 2019-06-22 12:17:34.404 T:3808412544   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:34.404 T:3808412544   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:34.410 T:3808412544   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:34.413 T:3808412544   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:34.413 T:3808412544   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:34.432 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:34.432 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:34.438 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:34.441 T:3635716992   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:34.441 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:34.447 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
> 2019-06-22 12:17:34.447 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
> 2019-06-22 12:17:34.452 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
> 2019-06-22 12:17:34.455 T:3635716992   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
> 2019-06-22 12:17:34.456 T:3635716992   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
> 2019-06-22 12:17:34.457 T:3635716992   DEBUG: [plugin.video.youtube] HTTPServer: Request uri path |/ping|
> 2019-06-22 12:17:34.457 T:3635716992   DEBUG: [plugin.video.youtube] HTTPServer: Connection from |127.0.0.1| Local range: |True|
> 2019-06-22 12:17:34.462 T:3808412544   DEBUG: [plugin.video.youtube] HTTPServer: Ping |127.0.0.1:50152| |204|
> 2019-06-22 12:17:35.565 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:35.566 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:35.566 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:35.577 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:36.281 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:36.290 T:4064941376   DEBUG: HandleKey: 166 (0xa6, obc89) pressed, action is Up
> 2019-06-22 12:17:36.314 T:4064941376   DEBUG: started alarm with name: setload
> 2019-06-22 12:17:37.204 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:37.204 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:37.213 T:4064941376   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
> 2019-06-22 12:17:37.213 T:4064941376   DEBUG: Activating window ID: 10004
> 2019-06-22 12:17:37.219 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:37.539 T:4064941376   DEBUG: ------ Window Deinit (Home.xml) ------
> 2019-06-22 12:17:37.539 T:4064941376   DEBUG: FreeVisualisation() done
> 2019-06-22 12:17:37.563 T:4064941376   DEBUG: ------ Window Init (Settings.xml) ------
> 2019-06-22 12:17:37.563 T:4064941376   DEBUG: Activating window ID: 10016
> 2019-06-22 12:17:37.564 T:4064941376   DEBUG: ------ Window Deinit (Settings.xml) ------
> 2019-06-22 12:17:37.564 T:4064941376   DEBUG: ------ Window Init (SettingsCategory.xml) ------
> 2019-06-22 12:17:38.842 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:39.251 T:3724485504   DEBUG: Previous line repeats 1 times.
> 2019-06-22 12:17:39.251 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:39.263 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:40.071 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:40.081 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:40.377 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:40.377 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:40.390 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:40.391 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:40.536 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:40.545 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:40.788 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:40.789 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:41.094 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:41.111 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:41.199 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:41.213 T:4064941376   DEBUG: HandleKey: 167 (0xa7, obc88) pressed, action is Down
> 2019-06-22 12:17:42.017 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:42.173 T:3724485504   DEBUG: Previous line repeats 1 times.
> 2019-06-22 12:17:42.173 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:42.181 T:4064941376   DEBUG: HandleKey: 168 (0xa8, obc87) pressed, action is Right
> 2019-06-22 12:17:43.655 T:3707700096   DEBUG: CWebServer[8089]: request received for /jsonrpc
> 2019-06-22 12:17:46.727 T:3724485504   DEBUG: Previous line repeats 3 times.
> 2019-06-22 12:17:46.727 T:3724485504   DEBUG: EventClient: button code 0 pressed
> 2019-06-22 12:17:46.747 T:4064941376   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
> 2019-06-22 12:17:46.747 T:4064941376  NOTICE: Disabled debug logging due to GUI setting. Level 0.
```

**Comment by XxAcielxX** [comment]
Ah, never mind. Fixed in 4.5.0 beta 3. Thanks
