### ISSUE TITLE
Signature function not found

### ISSUE THREAD

**Issue by mocarela** [jdf76/plugin.video.youtube#628]
Xbian on RPi… on more than 70% of YouTube stuff.

13:56:40  98.450844 T:1580516272  NOTICE: [plugin.video.youtube] Running: YouTube (6.4.1) on Jarvis (Kodi-16.1) with Python 2.7.9
                                            	Path: /play/
                                            	Params: {'video_id': '4d_xk7sSIbU'}
13:56:43 101.660698 T:1580516272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Signature function not found
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 31, in run
                                                results = provider.navigate(context)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 97, in navigate
                                                result = method(context, re_match)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 698, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 47, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 504, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1007, in _method_get_video_info
                                                parse_to_stream_list(url_encoded_fmt_stream_map)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 969, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 113, in get
                                                cached_data = partial_func()
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _load_json_script
                                                return self._load_javascript(javascript)
                                              File "/home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 60, in _load_javascript
                                                raise Exception('Signature function not found')
                                            Exception: Signature function not found
                                            -->End of Python script error report<--
13:56:43 101.893753 T:1952772096   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=4d_xk7sSIbU]

**Comment by nlack** [comment]
Same with my vero 4k
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Signature function not found
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 31, in run
                                                results = provider.navigate(context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 97, in navigate
                                                result = method(context, re_match)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 698, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 47, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 504, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 876, in _method_get_video_info
                                                cipher)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1117, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 113, in get
                                                cached_data = partial_func()
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _load_json_script
                                                return self._load_javascript(javascript)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 60, in _load_javascript
                                                raise Exception('Signature function not found')
                                            Exception: Signature function not found
                                            -->End of Python script error report<--
```

**Comment by bjorn055** [comment]
Can confirm this on my Xbian Pi too, signature function lost. Anoying but hope there is a fix soon.

**Comment by anxdpanic** [comment]
6.5.0~beta3 already includes the fix
Can find it @ https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

**Comment by mocarela** [comment]
Confirming 6.5.0~beta3 works.
