### ISSUE TITLE
Can't play some videos

### ISSUE THREAD

**Issue by Marra-CZ** [jdf76/plugin.video.youtube#633]
Running on Vero 4K+

Debug logs:

```
2019-06-25 21:41:06.730 T:3410244320  NOTICE: [plugin.video.youtube] Running: YouTube (6.4.1) on Leia (Kodi-18.3) with Python 2.7.13
                                                Path: /
                                                Params: {}
2019-06-25 21:41:07.946 T:3410244320  NOTICE: [plugin.video.youtube] Running: YouTube (6.4.1) on Leia (Kodi-18.3) with Python 2.7.13
                                                Path: /kodion/search/list/
                                                Params: {}
2019-06-25 21:41:08.386 T:3410244320  NOTICE: [plugin.video.youtube] Running: YouTube (6.4.1) on Leia (Kodi-18.3) with Python 2.7.13
                                                Path: /kodion/search/query/
                                                Params: {'q': 'funhouse'}
2019-06-25 21:41:10.549 T:3410244320  NOTICE: [plugin.video.youtube] Running: YouTube (6.4.1) on Leia (Kodi-18.3) with Python 2.7.13
                                                Path: /play/
                                                Params: {'video_id': 'Jdjtqu3XK4U'}
2019-06-25 21:41:12.762 T:3410244320   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Signature function not found
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 31, in run
                                                results = provider.navigate(context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 97, in navigate
                                                result = method(context, re_match)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 698, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 47, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 504, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 876, in _method_get_video_info
                                                cipher)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1117, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 113, in get
                                                cached_data = partial_func()
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _load_json_script
                                                return self._load_javascript(javascript)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 60, in _load_javascript
                                                raise Exception('Signature function not found')
                                            Exception: Signature function not found
                                            -->End of Python script error report<--
```

**Comment by anxdpanic** [comment]
Check for updates, v6.5.0 is on the official repository. The zip is also available https://github.com/jdf76/plugin.video.youtube/releases/tag/6.5.0 for manual updates.
