### ISSUE TITLE
live stream not working (log)

### ISSUE THREAD

**Issue by drrak** [jdf76/plugin.video.youtube#638]
_RPi3, Kodi 17.6, YT 6.5.0, LibreELEC 8.2.5_
```18:55:19.786 T:1945559040   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
18:55:22.488 T:1858073504  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.0) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'EcEMX-63PKY'}
18:55:25.106 T:1858073504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 31, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 97, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 722, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 46, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 898, in _method_get_video_info
                                                cipher)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1202, in generate_mpd
                                                discarded_streams.append(get_discarded_audio(mime, i, data[mime][i], 'no init or index'))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1027, in get_discarded_audio
                                                _discarded_stream['audio']['codec'] = str(stream['codecs'])
                                            TypeError: string indices must be integers, not str
                                            -->End of Python script error report<--
18:55:25.326 T:1945559040   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=EcEMX-63PKY]```

**Comment by virserg** [comment]
The same mistake on all streams.

**Comment by anxdpanic** [comment]
6.5.1~alpha1 should resolve the issue. https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

**Comment by virserg** [comment]
Thanks. Live streams work again.
