### ISSUE TITLE
Can't play videos from personal "Watch later" playlist

### ISSUE THREAD

**Issue by kuba-orlik** [jdf76/plugin.video.youtube#655]
Casting a video from a mobile browser to Kodi fails if the video was displayed as a part of a personal playlist, such as "Watch Later". I have to manually change the URL and then cast the video to Kodi

**Comment by anxdpanic** [comment]
Thanks for the report, when you have a chance please provide a complete debug log showing the issue.
https://kodi.wiki/view/Log_file

**Comment by anxdpanic** [comment]
Is case you're not aware there is also; https://kodi.tv/addon/scripts/tubecast

**Comment by kuba-orlik** [comment]
I will provide the log soon.

As per tubecase - I'm using [NewPipe](https://f-droid.org/en/packages/org.schabi.newpipe/), so it's probably out of the question?

**Comment by kuba-orlik** [comment]
Here's the debug log:

```
2019-09-01 19:50:33.153 T:1915175648   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
2019-09-01 19:50:33.153 T:1915175648   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
2019-09-01 19:50:33.201 T:1647280864   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Playlist.OnClear  - data: {"playlistid":1}
2019-09-01 19:50:33.202 T:1655673568   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnClear  - data: {"playlistid":1}
2019-09-01 19:50:33.208 T:1915175648   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
2019-09-01 19:50:33.208 T:1915175648   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
2019-09-01 19:50:33.287 T:1915188784   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/play/','4','?video_id=ar9WRwCiSr0&playlist_id=WL&order=default','resume:false')
2019-09-01 19:50:33.287 T:1163850464   DEBUG: Thread LanguageInvoker start, auto delete: false
2019-09-01 19:50:33.288 T:1163850464    INFO: initializing python engine.
2019-09-01 19:50:33.288 T:1163850464   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
2019-09-01 19:50:33.308 T:1550824160   DEBUG: Thread scriptobs start, auto delete: false
2019-09-01 19:50:33.398 T:1647280864   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"type":"unknown"},"playlistid":1,"position":0}
2019-09-01 19:50:33.506 T:1655673568   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"type":"unknown"},"playlistid":1,"position":0}
2019-09-01 19:50:33.508 T:1915188784   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-09-01 19:50:33.614 T:1163850464   DEBUG: -->Python Interpreter Initialized<--
2019-09-01 19:50:33.614 T:1163850464   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py"
2019-09-01 19:50:33.618 T:1163850464   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): setting the Python path to /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib:/home/osmc/.kodi/addons/script.module.certifi/lib:/home/osmc/.kodi/addons/script.module.chardet/lib:/home/osmc/.kodi/addons/script.module.idna/lib:/home/osmc/.kodi/addons/script.module.requests/lib:/home/osmc/.kodi/addons/script.module.six/lib:/home/osmc/.kodi/addons/script.module.urllib3/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
2019-09-01 19:50:33.618 T:1163850464   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib
2019-09-01 19:50:33.618 T:1163850464   DEBUG: CPythonInvoker(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.20.0 of the xbmc.python api
2019-09-01 19:50:36.281 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:50:36.282 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:50:36.288 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:50:36.291 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:50:36.292 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:50:36.294 T:1163850464   DEBUG: [plugin.video.youtube] send_notification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": true, "whitelist": "", "httpd_port": 50152}|
2019-09-01 19:50:36.296 T:1163850464   DEBUG: [plugin.video.youtube] JSONStore Load |/home/osmc/.kodi/userdata/addon_data/plugin.video.youtube/api_keys.json|
2019-09-01 19:50:36.298 T:1163850464   DEBUG: [plugin.video.youtube] JSONStore Load |/home/osmc/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
2019-09-01 19:50:36.312 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:50:36.312 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:50:36.318 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:50:36.321 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:50:36.321 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:50:36.329 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:50:36.329 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:50:36.335 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:50:36.338 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:50:36.339 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:50:36.346 T:1915175648   DEBUG: CAnnouncementManager - Announcement: check_settings from plugin.video.youtube
2019-09-01 19:50:36.347 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:50:36.347 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:50:36.347 T:1915175648   DEBUG: GOT ANNOUNCEMENT, type: 512, from plugin.video.youtube, message check_settings
2019-09-01 19:50:36.353 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:50:36.357 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:50:36.357 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:50:36.363 T:1647280864   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender plugin.video.youtube - method: Other.check_settings  - data: ["%7B%22httpd_address%22%3A%20%220.0.0.0%22%2C%20%22use_httpd%22%3A%20true%2C%20%22whitelist%22%3A%20%22%22%2C%20%22httpd_port%22%3A%2050152%7D"]
2019-09-01 19:50:36.364 T:1655673568   DEBUG: Skin Helper Service --> Kodi_Monitor: sender plugin.video.youtube - method: Other.check_settings  - data: ["%7B%22httpd_address%22%3A%20%220.0.0.0%22%2C%20%22use_httpd%22%3A%20true%2C%20%22whitelist%22%3A%20%22%22%2C%20%22httpd_port%22%3A%2050152%7D"]
2019-09-01 19:50:36.367 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:50:36.368 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:50:36.373 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:50:36.377 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:50:36.377 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:50:36.380 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.access_token) was not found.
2019-09-01 19:50:36.380 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.refresh_token) was not found.
2019-09-01 19:50:36.380 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.access_token.expires) was not found.
2019-09-01 19:50:36.380 T:1163850464   DEBUG: CSettingsManager: requested setting (youtube.api.last.hash) was not found.
2019-09-01 19:50:36.382 T:1163850464   DEBUG: [plugin.video.youtube] User: |0| Using API key set: |1|
2019-09-01 19:50:36.399 T:1680851680   DEBUG: [plugin.video.youtube] onNotification: |check_settings| -> |{"httpd_address": "0.0.0.0", "use_httpd": true, "whitelist": "", "httpd_port": 50152}|
2019-09-01 19:50:36.405 T:1163850464   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
2019-09-01 19:50:36.478 T:1163850464  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.3) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'playlist_id': 'WL', 'video_id': 'ar9WRwCiSr0', 'order': 'default'}
2019-09-01 19:50:36.481 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:50:36.481 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:50:36.487 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:50:36.490 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:50:36.491 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:50:36.587 T:1163850464   DEBUG: [plugin.video.youtube] JSONStore Load |/home/osmc/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
2019-09-01 19:50:36.591 T:1163850464   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
2019-09-01 19:50:36.593 T:1163850464   DEBUG: [plugin.video.youtube] Access token count: |2| Refresh token count: |2|
2019-09-01 19:50:36.595 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:50:36.595 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:50:36.601 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:50:36.605 T:1163850464   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:50:36.605 T:1163850464   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:50:36.606 T:1163850464   DEBUG: [plugin.video.youtube] User is logged in
2019-09-01 19:50:36.699 T:1915188784   DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------
2019-09-01 19:50:36.700 T:1163850464   DEBUG: [plugin.video.youtube] [data] v3 request: |GET| path: |playlistItems| params: |{'part': 'snippet', 'playlistId': 'WL', 'maxResults': '50'}| post_data: |None|
2019-09-01 19:50:37.330 T:1163850464 WARNING: [plugin.video.youtube] List of search result is empty
2019-09-01 19:50:37.402 T:1163850464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ZeroDivisionError'>
                                            Error Contents: float division by zero
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 97, in navigate
                                                result = method(context, re_match)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 724, in on_play
                                                return yt_play.play_playlist(self, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 170, in play_playlist
                                                progress_dialog = _load_videos()
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 139, in _load_videos
                                                _progress_dialog.update(steps=len(result), text=progress_text)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_progress_dialog_bg.py", line 34, in update
                                                position = int((100.0 / float(self._total)) * float(self._position))
                                            ZeroDivisionError: float division by zero
                                            -->End of Python script error report<--
2019-09-01 19:50:37.411 T:1163850464   DEBUG: onExecutionDone(12, /home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py)
2019-09-01 19:50:37.525 T:1915188784   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-09-01 19:50:37.661 T:1915188784   DEBUG: ------ Window Deinit (DialogExtendedProgressBar.xml) ------
2019-09-01 19:50:37.668 T:1163850464    INFO: Python interpreter stopped
2019-09-01 19:50:37.673 T:1163850464   DEBUG: Thread LanguageInvoker 1163850464 terminating
2019-09-01 19:50:37.684 T:1550824160   DEBUG: Thread scriptobs 1550824160 terminating
2019-09-01 19:50:37.684 T:1915188784   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-09-01 19:50:37.685 T:1915188784   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=ar9WRwCiSr0&playlist_id=WL&order=default]
2019-09-01 19:50:37.685 T:1915188784   DEBUG: Playlist Player: one or more items failed to play... aborting playback
2019-09-01 19:50:37.685 T:1915188784   DEBUG: ------ Window Init (DialogConfirm.xml) ------
2019-09-01 19:50:43.184 T:1915188784   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2019-09-01 19:51:07.426 T:1680851680   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:51:07.430 T:1680851680   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:51:07.463 T:1680851680   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:51:07.467 T:1680851680   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:51:07.468 T:1680851680   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:51:07.509 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:51:07.509 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:51:07.516 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:51:07.519 T:1468261088   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:51:07.520 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:51:07.525 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
2019-09-01 19:51:07.525 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
2019-09-01 19:51:07.531 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
2019-09-01 19:51:07.534 T:1468261088   DEBUG: CSettingsManager: requested setting (kodion.mpd.webm) was not found.
2019-09-01 19:51:07.534 T:1468261088   DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.mpd.webm. Creating a setting on-the-fly...
2019-09-01 19:51:07.535 T:1468261088   DEBUG: [plugin.video.youtube] HTTPServer: Request uri path |/ping|
2019-09-01 19:51:07.536 T:1468261088   DEBUG: [plugin.video.youtube] HTTPServer: Connection from |127.0.0.1| Local range: |True|
2019-09-01 19:51:07.560 T:1680851680   DEBUG: [plugin.video.youtube] HTTPServer: Ping |127.0.0.1:50152| |204|

```

**Comment by vdbpeter** [comment]
Hi, thanks for your efforts on this module. 

Having followed your procedure setting up my own Google APIv3, (https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys) I too am having problems accessing most of the menu items. From the kodi.log, this is the typical error message:
2020-07-27 14:55:11.913 T:1544475504   ERROR: [plugin.video.youtube] Error reason: |forbidden| with message: |Requests to this API youtube method youtube.api.v3.V3DataPlaylistItemService.List are blocked.|

I can access: "My Subscriptions", "Disliked Videos","History". The rest are blocked ("forbidden").

Any help appreciated.
Thanks
