### ISSUE TITLE
Unable to play some videos

### ISSUE THREAD

**Issue by SonOfDiablo** [jdf76/plugin.video.youtube#659]
I have noticed that the YouTube plug-in is unable to play some videos in certain circumstances.

Examples being these:
https://youtu.be/oCp_2hqguUg
https://youtu.be/MOxWEDExpWI

I was able to play them in 360p, but when I try in 720p Kodi loads for a bit and then return to the video list. 

I'm using LibreElec 9.1.002 (Kodi 18.3) on a Raspberry Pi 3 b+

Log: http://ix.io/1Uwl

**Comment by alephnull** [comment]
I have a different error:
2019-09-11 19:48:07.449 T:3469087600  NOTICE: URLResolver: Initializing URLResolver version: 2.10.0
2019-09-11 19:48:08.099 T:3469087600  NOTICE: URLResolver: No Settings Update Needed
2019-09-11 19:48:09.552 T:3562009456  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.2) with Python 2.7.15
                                            	Path: /
                                            	Params: {'action': 'play_video', 'videoid': 'UnmSJZGSgEk'}
2019-09-11 19:48:09.583 T:3562009456 WARNING: [plugin.video.youtube] DEPRECATED "plugin://plugin.video.youtube/?action=play_video&videoid=UnmS
JZGSgEk"
2019-09-11 19:48:09.583 T:3562009456 WARNING: [plugin.video.youtube] USE INSTEAD "plugin://plugin.video.youtube/play/?video_id=UnmSJZGSgEk"
2019-09-11 19:48:12.552 T:3562009456   ERROR: Traceback (most recent call last):
2019-09-11 19:48:12.552 T:3562009456   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/y
t_play.py", line 46, in play_video
2019-09-11 19:48:12.557 T:3562009456   ERROR:     video_streams = client.get_video_streams(context, video_id)
2019-09-11 19:48:12.557 T:3562009456   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/y
outube.py", line 96, in get_video_streams
2019-09-11 19:48:12.558 T:3562009456   ERROR:     video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
2019-09-11 19:48:12.559 T:3562009456   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v
ideo_info.py", line 505, in load_stream_infos
2019-09-11 19:48:12.560 T:3562009456   ERROR:     return self._method_get_video_info(video_id, player_config, cookies)
2019-09-11 19:48:12.560 T:3562009456   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v
ideo_info.py", line 1015, in _method_get_video_info
2019-09-11 19:48:12.560 T:3562009456   ERROR:     raise YouTubeException('No streams found')
2019-09-11 19:48:12.561 T:3562009456   ERROR: YouTubeException: No streams found
2019-09-11 19:48:12.561 T:3562009456   ERROR: [plugin.video.youtube] None
2019-09-11 19:48:12.592 T:4086624272   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.reddit_viewer/?url=htt
p%3A%2F%2Fyoutube.com%2Fv%2FUnmSJZGSgEk&mode=playYTDLVideo&name=Declassified%3A+Espionage+%3A+The+Trigon+KGB+Chess+Game+%282019%29+-+The+CIA+r
ecruits+Soviet+diplomat+Aleksandr+Ogorodnik%2C+codename+TRIGON%2C+to+capture+intelligence+on+the+Soviet+Union+during+the+peak+of+the+Cold+War+
conflict.&type=https%3A%2F%2Fexternal-preview.redd.it%2FxThmJn_RjThzGagqHZDd8cPbWpn4_lYDmz5mITTe9io.jpg%3Fauto%3Dwebp%26s%3D58f89b7ad03d7c4c25
c0f59c3d25894ef7095c11]
```

```

**Comment by dydemin** [comment]
Also have simular issue. I'm using OSMC on the same device. Firstly tried to play [this](https://youtu.be/B3w6aASXaa4) video. But in fact it's hard to find what video would be playing, no any video is playing.

I think this part of log could be useful:
```
2019-09-11 21:11:40.251 T:1495266016  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.3) with Python 2.7.13
                                            	Path: /config/mpd/
                                            	Params: {}
2019-09-11 21:12:04.285 T:1761600224 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
2019-09-11 21:12:05.056 T:1761600224 WARNING: Previous line repeats 1 times.
2019-09-11 21:12:05.056 T:1761600224  NOTICE: LoadJpeg: unable to load http://download.osmc.tv/kodi/addons/leia/plugin.video.ad6/resources/media/ad6_large.jpg
2019-09-11 21:12:10.568 T:1495266016  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.3) with Python 2.7.13
                                            	Path: /config/mpd/
                                            	Params: {}
2019-09-11 21:15:52.859 T:1915270704   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2019-09-11 21:15:55.764 T:1495266016  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.3) with Python 2.7.13
                                            	Path: /kodion/search/list/
                                            	Params: {}
2019-09-11 21:15:57.055 T:1495266016  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.3) with Python 2.7.13
                                            	Path: /kodion/search/query/
                                            	Params: {'q': '\xd0\x9c\xd0\xb0\xd1\x88\xd0\xb0 \xd0\xb8 \xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb2\xd0\xb5\xd0\xb4\xd1\x8c '}
2019-09-11 21:16:05.375 T:1495266016  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.3) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'B3w6aASXaa4'}
2019-09-11 21:16:09.353 T:1495266016   ERROR: Traceback (most recent call last):
2019-09-11 21:16:09.353 T:1495266016   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 46, in play_video
2019-09-11 21:16:09.353 T:1495266016   ERROR:     video_streams = client.get_video_streams(context, video_id)
2019-09-11 21:16:09.353 T:1495266016   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
2019-09-11 21:16:09.353 T:1495266016   ERROR:     video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
2019-09-11 21:16:09.353 T:1495266016   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
2019-09-11 21:16:09.353 T:1495266016   ERROR:     return self._method_get_video_info(video_id, player_config, cookies)
2019-09-11 21:16:09.353 T:1495266016   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1015, in _method_get_video_info
2019-09-11 21:16:09.353 T:1495266016   ERROR:     raise YouTubeException('No streams found')
2019-09-11 21:16:09.354 T:1495266016   ERROR: YouTubeException: No streams found
2019-09-11 21:16:09.354 T:1495266016   ERROR: [plugin.video.youtube] None
2019-09-11 21:16:09.357 T:1915270704   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=B3w6aASXaa4]
2019-09-11 21:16:17.752 T:1495266016  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Leia (Kodi-18.3) with Python 2.7.13
                                            	Path: /kodion/search/list/
                                            	Params: {}
```

**Comment by omarroth** [comment]
Likely related: fent/node-ytdl-core#486, TeamNewPipe/NewPipe#2615, Tyrrrz/YoutubeExplode#296.

**Comment by a26364177** [comment]
temp fix like this
https://github.com/ytdl-org/youtube-dl/commit/bf1317d257d13188601c837c983830355c6203e5

**Comment by anxdpanic** [comment]
The issue reported by @SonOfDiablo is different, from the reponses. The reported issue appears to be on YouTube's end, and no fix in sight(unless the fix for todays issue does the trick). See #661 for the issue with no videos working.
