### ISSUE TITLE
Error opening some videos.

### ISSUE THREAD

**Issue by rsantellan** [jdf76/plugin.video.youtube#678]
Hi,
I have an old Raspberry pi 2 B+ with Kodi 14.1 installed, I know that are new versions but is possible to some way fix this ? 
`
21:17:34 T:2868900928  NOTICE: Thread BackgroundLoader start, auto delete: false
21:17:35 T:2868900928  NOTICE: Thread LanguageInvoker start, auto delete: false
21:17:35 T:2868900928  NOTICE: -->Python Interpreter Initialized<--
21:17:39 T:2868900928  NOTICE: [plugin.video.youtube] Running: YouTube (5.4.9) on Helix (Kodi-14.1) with Python 2.7.3
21:17:45 T:2868900928   ERROR: /home/pi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:335: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              SNIMissingWarning
21:17:45 T:2868900928   ERROR: /home/pi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:133: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
21:17:45 T:2868900928   ERROR: /home/pi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
21:17:46 T:2868900928   ERROR: /home/pi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:133: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
21:17:46 T:2868900928   ERROR: /home/pi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
21:18:15 T:2868900928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 40, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 24, in run
                                                results = provider.navigate(context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 87, in navigate
                                                result = method(context, re_match)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 11, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 475, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 19, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 79, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 403, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 738, in _method_get_video_info
                                                parse_to_stream_list(url_encoded_fmt_stream_map)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 700, in parse_to_stream_list
                                                url += '&signature=%s' % cipher.get_signature(stream_map['s'])
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 23, in get_signature
                                                func = self._parse_sig_js(javascript)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _parse_sig_js
                                                funcname = match.group('sig')
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
21:18:15 T:3038490624   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=luwAMFcc2f8]
21:18:27 T:2868900928  NOTICE: Thread BackgroundLoader start, auto delete: false
21:18:28 T:2868900928  NOTICE: Thread JobWorker start, auto delete: true
21:18:29 T:2822624320  NOTICE: Previous line repeats 1 times.
21:18:29 T:2822624320  NOTICE: Thread LanguageInvoker start, auto delete: false
21:18:29 T:2822624320  NOTICE: -->Python Interpreter Initialized<--
`

I can't format to install a new version, because I can't mess with the installation (I don't know if all will work again)
Any ideas how to fix this ?
Thanks in advance.

**Comment by anxdpanic** [comment]
Sorry, the only way to fix this is to update.
If you're worried up the the upgrade, you can create an backup image of the sdcard in it's current state before attempting upgrade. Depending on the OS you may not even need a format.

**Comment by rsantellan** [comment]
Thanks @anxdpanic for the response. I will try to update the kodi. Regards

**Comment by Maranobarbaro** [comment]
Hi. I'm in the same situation. I use a old x86 running kodi 14.2. The problem is that this should be the last build (openelec 5.0.8) for my eeepc. I cannot upgrade to Plugin higher than 5.4.8. Some videos doesn't start telling "script failed!". I searched everywhere for a solution and the only one is to cast a YouTube video from Android using Yatse. Please help me. Thanks in advance

**Comment by anxdpanic** [comment]
@Maranobarbaro The same response applies, the only way to fix this is to update.

**Comment by Maranobarbaro** [comment]
So this mean no solution for this x86 device or do you suggest me any other way?
