### ISSUE TITLE
Purchased movie image stalls after a few minutes

### ISSUE THREAD

**Issue by MartChic** [jdf76/plugin.video.youtube#716]
I am trying to play a movie purchased on youtube. I starts well but the image stalls after a few minutes (the sound continues though). Here is the log:

`2020-01-12 08:27:56.097 T:1229976448 WARNING: Previous line repeats 56810 times.
2020-01-12 08:27:56.097 T:1229976448  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.2) on Leia (Kodi-18.5) with Python 2.7.16
                                            	Path: /play/
                                            	Params: {'video_id': 'aFVaqjUTQfM'}
2020-01-12 08:27:56.546 T:1148175232 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-01-12 08:27:58.984 T:1229976448 WARNING: Previous line repeats 4 times.
2020-01-12 08:27:58.984 T:1229976448   ERROR: Traceback (most recent call last):
2020-01-12 08:27:58.984 T:1229976448   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 46, in play_video
2020-01-12 08:27:58.988 T:1229976448   ERROR:     video_streams = client.get_video_streams(context, video_id)
2020-01-12 08:27:58.988 T:1229976448   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
2020-01-12 08:27:58.992 T:1229976448   ERROR:     video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
2020-01-12 08:27:58.992 T:1229976448   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
2020-01-12 08:27:58.998 T:1229976448   ERROR:     return self._method_get_video_info(video_id, player_config, cookies)
2020-01-12 08:27:58.998 T:1229976448   ERROR:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 890, in _method_get_video_info
2020-01-12 08:27:58.998 T:1229976448   ERROR:     raise YouTubeException('Proxy is not running')
2020-01-12 08:27:58.998 T:1229976448   ERROR: YouTubeException: Proxy is not running
2020-01-12 08:27:58.998 T:1229976448   ERROR: [plugin.video.youtube] None
2020-01-12 08:27:59.229 T:1148175232 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-01-12 08:29:14.632 T:1229976448 WARNING: Previous line repeats 150 times.
2020-01-12 08:29:14.632 T:1229976448  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.2) on Leia (Kodi-18.5) with Python 2.7.16
                                            	Path: /play/
                                            	Params: {'video_id': 'aFVaqjUTQfM'}
2020-01-12 08:29:15.020 T:1148175232 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-01-12 08:29:17.503 T:1937689024 WARNING: Previous line repeats 4 times.
2020-01-12 08:29:17.503 T:1937689024  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=aFVaqjUTQfM
2020-01-12 08:29:17.627 T:1095320448  NOTICE: Creating InputStream
2020-01-12 08:29:17.648 T:1095320448   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2020-01-12 08:29:20.748 T:1095320448  NOTICE: Creating Demuxer
2020-01-12 08:29:20.749 T:1095320448  NOTICE: Opening stream: 1 source: 256
2020-01-12 08:29:20.978 T:1095320448  NOTICE: Creating video codec with codec id: 27
2020-01-12 08:29:20.986 T:1095320448  NOTICE: Opening stream: 2 source: 256
2020-01-12 08:29:21.077 T:1095320448  NOTICE: Finding audio codec for: 86018
2020-01-12 08:29:21.078 T:1095320448  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-01-12 08:29:21.640 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 31Ó
2020-01-12 08:29:21.647 T:1044964224   ERROR: Previous line repeats 16 times.
2020-01-12 08:29:21.647 T:1044964224  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2020-01-12 08:29:21.651 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 31Ó
2020-01-12 08:29:23.945 T:1095320448   ERROR: Previous line repeats 182 times.
2020-01-12 08:29:23.945 T:1095320448  NOTICE: Closing stream player 1
2020-01-12 08:29:23.946 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 31Ó
2020-01-12 08:29:23.946 T:1095320448  NOTICE: Waiting for audio thread to exit
2020-01-12 08:29:23.960 T:1044964224  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-01-12 08:29:23.960 T:1095320448  NOTICE: Closing audio device
2020-01-12 08:29:24.011 T:1095320448  NOTICE: Deleting audio codec
2020-01-12 08:29:24.012 T:1095320448  NOTICE: Opening stream: 2 source: 256
2020-01-12 08:29:24.153 T:1095320448  NOTICE: Finding audio codec for: 86018
2020-01-12 08:29:24.154 T:1095320448  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-01-12 08:29:24.154 T:1095320448  NOTICE: Creating audio thread
2020-01-12 08:29:24.154 T:1061749632  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-01-12 08:29:25.421 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 31Ó
2020-01-12 08:29:25.431 T:1061749632   ERROR: Previous line repeats 47 times.
2020-01-12 08:29:25.432 T:1061749632  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2020-01-12 08:29:25.435 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 31Ó
2020-01-12 08:29:27.072 T:1148175232   ERROR: Previous line repeats 79 times.
2020-01-12 08:29:27.072 T:1148175232 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-01-12 08:29:38.538 T:1148175232 WARNING: Previous line repeats 9 times.
2020-01-12 08:29:38.539 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 31Ó
2020-01-12 08:29:43.597 T:1148175232   ERROR: Previous line repeats 255 times.
2020-01-12 08:29:43.597 T:1148175232 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-01-12 08:34:17.509 T:1148175232 WARNING: Previous line repeats 14 times.
2020-01-12 08:34:17.509 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.519 T:1095320448   ERROR: Previous line repeats 78 times.
2020-01-12 08:34:17.519 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.519 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.520 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.520 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.521 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.521 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.521 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.522 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.522 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.522 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.523 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.523 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.524 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.524 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.524 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.525 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.525 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.525 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.526 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.526 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.526 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.527 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.527 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.527 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.528 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.528 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.528 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.528 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.529 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.529 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.529 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.530 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.530 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.530 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.531 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.531 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.531 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.532 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.532 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.532 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.533 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.533 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.533 T:1148175232   ERROR: Previous line repeats 2 times.
2020-01-12 08:34:17.534 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.534 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.535 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.535 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.535 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.536 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.536 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.536 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.536 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.537 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.537 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.537 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.538 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.538 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.538 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.539 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.539 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.539 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.540 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.540 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.540 T:1148175232   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.541 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.541 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.541 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.544 T:1095320448   ERROR: Previous line repeats 22 times.
2020-01-12 08:34:17.544 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.544 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.544 T:1095320448   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.545 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.545 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.545 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.545 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.546 T:1095320448   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.546 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.546 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.546 T:1095320448   ERROR: Previous line repeats 1 times.
2020-01-12 08:34:17.546 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.546 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:17.547 T:1095320448   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-01-12 08:34:17.547 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:25.664 T:1061749632   ERROR: Previous line repeats 630 times.
2020-01-12 08:34:25.665 T:1061749632  NOTICE: CVideoPlayerAudio::Process - stream stalled
2020-01-12 08:34:25.766 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:58.785 T:1937689024   ERROR: Previous line repeats 2146 times.
2020-01-12 08:34:58.785 T:1937689024  NOTICE: CVideoPlayer::CloseFile()
2020-01-12 08:34:58.796 T:1095320448  NOTICE: CVideoPlayer::OnExit()
2020-01-12 08:34:58.796 T:1095320448  NOTICE: Closing stream player 1
2020-01-12 08:34:58.797 T:1095320448  NOTICE: Waiting for audio thread to exit
2020-01-12 08:34:58.797 T:1061749632   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2020-01-12 08:34:58.797 T:1061749632  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-01-12 08:34:58.797 T:1095320448  NOTICE: Closing audio device
2020-01-12 08:34:58.813 T:1095320448  NOTICE: Deleting audio codec
2020-01-12 08:34:58.814 T:1095320448  NOTICE: Closing stream player 2
2020-01-12 08:34:58.821 T:1937689024  NOTICE: VideoPlayer: waiting for threads to exit
2020-01-12 08:34:58.821 T:1148175232   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key 5236FA4683EB5E1C9A35369B8C51DAFD
2020-01-12 08:34:58.859 T:1188012928   ERROR: EXCEPTION: XBMC is not playing any media file
2020-01-12 08:34:58.919 T:1095320448  NOTICE: waiting for video thread to exit
2020-01-12 08:34:58.919 T:1148175232   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2020-01-12 08:34:58.919 T:1148175232  NOTICE: thread end: video_thread
2020-01-12 08:34:58.919 T:1095320448  NOTICE: deleting video codec
2020-01-12 08:34:58.959 T:1188012928   ERROR: EXCEPTION: XBMC is not playing any media file
2020-01-12 08:34:59.592 T:1937689024   ERROR: Previous line repeats 6 times.
2020-01-12 08:34:59.592 T:1937689024  NOTICE: VideoPlayer: finished waiting
2020-01-12 08:34:59.592 T:1937689024  NOTICE: CVideoPlayer::CloseFile()
2020-01-12 08:34:59.593 T:1937689024  NOTICE: VideoPlayer: waiting for threads to exit
2020-01-12 08:34:59.593 T:1937689024  NOTICE: VideoPlayer: finished waiting
2020-01-12 08:34:59.670 T:1188012928   ERROR: EXCEPTION: XBMC is not playing any media file
2020-01-12 08:37:29.557 T:1937689024   ERROR: Previous line repeats 1 times.
2020-01-12 08:37:29.558 T:1937689024   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't
2020-01-12 08:37:29.560 T:1937689024  NOTICE: LoadJpeg: unable to load `

**Comment by anxdpanic** [comment]
They seem to be pretty imprecise about which qualities are permitted, so this happens sometimes. 

For that purchase you can
- set InputStream Adaptive -> `Settings -> Stream selection -> manual`
- change video stream during playback to preferred working resolution

**Comment by AdrianLeal** [comment]
I have exactly the same issue with the purchased movies, they start but after some minutes stall,, the same error in the logs (sample below), I'm using version 6.8.2 on kodi 18.6 on a raspberry running raspbian buster. I tried setting stream selection to manual but i can not figure out which resolution to use i tied different with exactly the same result, stream stalled after some minutes  (around 5)

Any other setting i can try?. thanks in advance

2020-05-26 12:52:22.596 T:1346363616   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-05-26 12:52:22.596 T:1613557984   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key F41612B5C71C5EE8880EC1E4F57FAD86
2020-05-26 12:52:22.596 T:1346363616   ERROR: Previous line repeats 1 times.
2020-05-26 12:52:22.596 T:1346363616   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-05-26 12:52:22.596 T:1613557984   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key F41612B5C71C5EE8880EC1E4F57FAD86
2020-05-26 12:52:22.597 T:1346363616   ERROR: Previous line repeats 1 times.
2020-05-26 12:52:22.597 T:1346363616   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-05-26 12:52:22.597 T:1613557984   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key F41612B5C71C5EE8880EC1E4F57FAD86
2020-05-26 12:52:22.597 T:1346363616   ERROR: Previous line repeats 1 times.
2020-05-26 12:52:22.597 T:1346363616   ERROR: AddOnLog: InputStream Adaptive: Decrypt Sample returns failure!
2020-05-26 12:52:22.597 T:1613557984   ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key F41612B5C71C5EE8880EC1E4F57FAD86
2020-05-26 12:52:30.754 T:1228927200   ERROR: Previous line repeats 5547 times.
2020-05-26 12:52:30.754 T:1228927200  NOTICE: CVideoPlayerAudio::Process - stream stalled

**Comment by DitDitGitHub** [comment]
Same problem here. A fix would be greatly appreciated.

**Comment by tanty** [comment]
I can confirm with the latest Kodi (Leia), YouTube plugin and a recently installed Widevine.

**Comment by tanty** [comment]
@peak3d, maybe you have some insight on this problem?

**Comment by tanty** [comment]
> They seem to be pretty imprecise about which qualities are permitted, so this happens sometimes.
> 
> For that purchase you can
> 
> * set InputStream Adaptive -> `Settings -> Stream selection -> manual`
> * change video stream during playback to preferred working resolution

Just to make it explicit. I got an HD purchase, set the "stream selection" to "manual", and I can reproduce this problem with:
* h264, 1920x1080, 9286049 bps
* h264, 1280x720, 5864836 bps
* h264, 640x360, 638688 bps
* h264, 256x144, 144731 bps

I can provide a full debug log if needed.

**Comment by peak3d** [comment]
I'll try to reproduce later

Edit: @tanty pls. provide a full debug log (for first no component debugging enabled)
What's the name / id of the purchased stream?

**Comment by tanty** [comment]
Movie:

https://play.google.com/store/movies/details/Knives_Out?id=kRAMFu8Apz0.P

@peak3d, I'll send you the full debug log directly by mail in a few minutes. I don't want to put it publicly here.

**Comment by tanty** [comment]
@peak3d any luck with this?
