### ISSUE TITLE
KeyError: u'splice'

### ISSUE THREAD

**Issue by sowdust** [jdf76/plugin.video.youtube#723]
Hello, one of the latest commits introduced the following problem on LibreELEC:

```
13:36:54.299 T:1111389088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'splice'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 97, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 724, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 46, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1029, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 991, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _load_json_script
                                                return self._load_javascript(javascript)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 98, in _load_javascript
                                                _function = self._get_object_function(object_name, function_name, javascript)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 199, in _get_object_function
                                                return self._object_cache[object_name][function_name]
                                            KeyError: u'splice'
                                            -->End of Python script error report<--

```

**Comment by anxdpanic** [comment]
One of the recent commits was a fix for this issue, this was a change by YouTube twp days ago.

https://github.com/jdf76/plugin.video.youtube/issues/719

**Comment by Genato** [comment]
> One of the recent commits was a fix for this issue, this was a change by YouTube two days ago.
> 
> #719

I'm sorry for commenting in closed topic but this issue still persists.
Just freshly updated YoutTube on Kodi LibreELEC (anxdpanic, bromix . 6.8.2)
