### ISSUE TITLE
Addon won't start 

### ISSUE THREAD

**Issue by oCanna** [jdf76/plugin.video.youtube#733]
> 2020-02-01 10:16:12.139 T:3575096192  NOTICE: [plugin.video.youtube] Running: YouTube (6.6.0) on Leia (Kodi-18.5) with Python 2.7.16
                                                Path: /
                                                Params: {}
2020-02-01 10:16:13.287 T:3575096192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error reason: |keyExpired| with message: |Bad Request|
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 99, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 132, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1485, in on_root
                                                playlists = resource_manager.get_related_playlists(channel_id='mine')
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 183, in get_related_playlists
                                                result = self._update_channels([channel_id])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 78, in _update_channels
                                                if self.handle_error(json_data):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 240, in handle_error
                                                raise Exception(error_message)
                                            Exception: Error reason: |keyExpired| with message: |Bad Request|
                                            -->End of Python script error report<--
2020-02-01 10:16:13.463 T:3583488896   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
2020-02-01 10:16:13.469 T:4093169680   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed

**Comment by oCanna** [comment]
For some reasons, it is working again.
