### ISSUE TITLE
Version 6.6.0 is brocken with Kodi 18

### ISSUE THREAD

**Issue by radasbona** [jdf76/plugin.video.youtube#738]
Hi, here is the Log File. I'm running latest stable libreelec on raspberry 1B.

2020-02-20 19:36:15.263 T:1720898432  NOTICE: [plugin.video.youtube] Running: YouTube (6.6.0) on Leia (Kodi-18.5) with Python 2.7.16
                                            	Path: /play/
                                            	Params: {'video_id': 'diYAc7gB-0A'}
2020-02-20 19:36:26.076 T:1720898432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error reason: |accessNotConfigured| with message: |Project 294899064488 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.|
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 99, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 749, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 86, in play_video
                                                use_play_data=playback_history)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 411, in update_play_info
                                                video_data = resource_manager.get_videos([video_id])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 138, in get_videos
                                                result.update(self._update_videos(list_of_50, live_details))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 121, in _update_videos
                                                if self.handle_error(json_data):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 240, in handle_error
                                                raise Exception(error_message)
                                            Exception: Error reason: |accessNotConfigured| with message: |Project 294899064488 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.|
                                            -->End of Python script error report<--

**Comment by anxdpanic** [comment]
See #736

**Comment by radasbona** [comment]
Ups. Sorry. 
And thanks for the workaround.
