### ISSUE TITLE
Fail with InsecureRequestWarning / PythonToCppException

### ISSUE THREAD

**Issue by petterreinholdtsen** [jdf76/plugin.video.youtube#744]
When trying to play a youtube video (https://www.youtube.com/watch?v=gHOKrHrmCbQ) in Kodi, the playout fail and tell me to have a look in the logs.  My kodi is not configured to log into youtube, so this is unauthenticated access.

This show up in the log when I send the 'play video' request using the kodi API:

```
2020-02-29 13:00:41.611 T:1562395520  NOTICE: [plugin.video.youtube] Running: YouTube (6.6.0) on Leia (Kodi-18.5) with Python 2.7.16
                                                Path: /play/
                                                Params: {'screensaver': 'true', 'video_id': 'gHOKrHrmCbQ', 'incognito': 'true'}
2020-02-29 13:00:41.779 T:1562395520   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2020-02-29 13:00:43.487 T:1562395520   ERROR: Previous line repeats 2 times.
2020-02-29 13:00:43.488 T:1562395520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error reason: |accessNotConfigured| with message: |Project 294899064488 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.|
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 99, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 749, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 86, in play_video
                                                use_play_data=playback_history)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 411, in update_play_info
                                                video_data = resource_manager.get_videos([video_id])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 138, in get_videos
                                                result.update(self._update_videos(list_of_50, live_details))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 121, in _update_videos
                                                if self.handle_error(json_data):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 240, in handle_error
                                                raise Exception(error_message)
                                            Exception: Error reason: |accessNotConfigured| with message: |Project 294899064488 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.|
                                            -->End of Python script error report<--
```

Did something change in the Youtube end making my kodi add-on fail to work?

**Comment by anxdpanic** [comment]
See #736
