### ISSUE TITLE
unable to load youtube plugin

### ISSUE THREAD

**Issue by thelacesz** [jdf76/plugin.video.youtube#756]
Hello dear Developer!

My config:
Raspberry pi 3
LibreELEC 9.2.0
YouTube plugin 6.6.0

I've set everything up to log in. API, Google, etc.

the startup fails

I have error:

` ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                                                            - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>                                                                                                                                                      Error Contents: list index out of range                                                                                                                                                         Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>                                                                                                  runner.run(__provider__)                                                                                                                                                                      File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run                                                                                  __RUNNER__.run(provider, context)                                                                                                                                                             File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run                                                                   results = provider.navigate(context)                                                                                                                                                          File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 99, in navigate                                                                  result = method(context, re_match)                                                                                                                                                            File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 132, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1485, in on_root
                                                playlists = resource_manager.get_related_playlists(channel_id='mine')
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 183, in get_related_playl>                                                result = self._update_channels([channel_id])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 50, in _update_channels
                                                channel_id = items[0]['id']                                                                                                                                                                 IndexError: list index out of range
                                            -->End of Python script error report<--`

``

**Comment by anxdpanic** [comment]
@thelacesz 
Installing the beta should resolve the issue, you can find it https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.0-dev

**Comment by ilakast** [comment]
Thanks @anxdpanic 
I had the exact same error and your solution worked
