### ISSUE TITLE
ValueError: time data [..] does not match format [..] when browsing a channel

### ISSUE THREAD

**Issue by allixx** [jdf76/plugin.video.youtube#779]
I've encountered an error while trying to browse a random channel. A few other channels I've also tried browse without errors, but not this one. 

```
2020-04-08 22:11:32.280 T:139890019927808  NOTICE: [plugin.video.youtube] Running: YouTube (6.7.0) on Leia (Kodi-18.6) with Python 2.7.16
                                                Path: /channel/UCfCRDwiCae7UWjBkSuDPnXw/
                                                Params: {}
2020-04-08 22:11:33.118 T:139890019927808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: time data u'2020-04-02T06:34:46Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 631, in _on_channel
                                                v3.response_to_items(self, context, json_data, sort=lambda x: x.get_aired(), reverse_sort=True))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 269, in response_to_items
                                                result.extend(_process_list_response(provider, context, json_data))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 253, in _process_list_response
                                                live_details=is_upcoming, use_play_data=use_play_data)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 292, in update_video_infos
                                                video_item.set_aired_utc(utils.datetime_parser.strptime(snippet['publishedAt']))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/datetime_parser.py", line 176, in strptime
                                                return datetime(*time.strptime(s, fmt)[:6])
                                              File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
                                              File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
                                            ValueError: time data u'2020-04-02T06:34:46Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            -->End of Python script error report<--
2020-04-08 22:11:33.202 T:139888974075648   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/channel/UCfCRDwiCae7UWjBkSuDPnXw/
2020-04-08 22:11:33.237 T:139890153093248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/channel/UCfCRDwiCae7UWjBkSuDPnXw/) failed
```

That's on LibreELEC 9.2.1 x86_64 official build, with Kodi 18.6. A common setup with properly filled and working API keys etc.

**Comment by anxdpanic** [comment]
See https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev for 6.7.1~alpha1, should fix the issue.

**Comment by allixx** [comment]
Thank you, the fix helped!
