### ISSUE TITLE
Error Contents: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by mvrk69** [jdf76/plugin.video.youtube#815]
Hi,

Since today i can't play some videos:

2020-05-06 13:30:26.890 T:3653206896  NOTICE: [plugin.video.youtube] Running: YouTube (6.8.0) on Leia (Kodi-18.2) with Python 2.7.15
                                            	Path: /
                                            	Params: {}
2020-05-06 13:30:30.999 T:3653206896  NOTICE: [plugin.video.youtube] Running: YouTube (6.8.0) on Leia (Kodi-18.2) with Python 2.7.15
                                            	Path: /channel/mine/playlists/
                                            	Params: {}
2020-05-06 13:30:34.754 T:3653206896  NOTICE: [plugin.video.youtube] Running: YouTube (6.8.0) on Leia (Kodi-18.2) with Python 2.7.15
                                            	Path: /channel/mine/playlist/PL20c6qQKeCXQjMFibLpXdYpuAcOToewEk/
                                            	Params: {}
2020-05-06 13:30:37.727 T:3653206896  NOTICE: [plugin.video.youtube] Running: YouTube (6.8.0) on Leia (Kodi-18.2) with Python 2.7.15
                                            	Path: /play/
                                            	Params: {'video_id': 'AT6fZSxAiKU'}
2020-05-06 13:30:39.824 T:3653206896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'split'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 763, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 929, in _method_get_video_info
                                                cipher)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1221, in generate_mpd
                                                url = urllib.parse.unquote(stream_map.get('url'))
                                              File "/usr/lib/python2.7/urllib.py", line 1233, in unquote
                                            AttributeError: 'NoneType' object has no attribute 'split'
                                            -->End of Python script error report<--
2020-05-06 13:30:40.037 T:4093702160   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=AT6fZSxAiKU]

**Comment by anxdpanic** [comment]
@mvrk69 Thanks for the heads up
https://github.com/jdf76/plugin.video.youtube/releases/tag/6.x.x-dev <- test zips are here with the fix

**Comment by mvrk69** [comment]
Thanks for the quick fix. Its working fine now!

**Comment by anxdpanic** [comment]
6.8.1 is waiting review on the official repository, release available: https://github.com/jdf76/plugin.video.youtube/releases/tag/6.8.1
