### ISSUE TITLE
Videos will not play, error trying to play them

### ISSUE THREAD

**Issue by sbstp** [jdf76/plugin.video.youtube#849]
I'm using the "Play to Kodi" extension to send the video of my Kodi box.
Kodi version: 9.0.2
Plugin version: 6.8.2

Kodi log:
```
2020-07-27 23:56:17.576 T:3606025072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'splice'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 763, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 100, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1047, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1009, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _load_json_script
                                                return self._load_javascript(javascript)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 98, in _load_javascript
                                                _function = self._get_object_function(object_name, function_name, javascript)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 200, in _get_object_function
                                                return self._object_cache[object_name][function_name]
                                            KeyError: u'splice'
                                            -->End of Python script error report<--
2020-07-27 23:56:17.761 T:4089704464   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=ebb8baFaQ-s]
```

**Comment by sbstp** [comment]
Some videos play and others do not:  
This one plays: https://www.youtube.com/watch?v=uWFPTbrLOlg  
This one does not: https://www.youtube.com/watch?v=ebb8baFaQ-s

**Comment by mvrk69** [comment]
I have same problem, some videos play others don't.

This one for example doesn't:

https://www.youtube.com/watch?v=ZBoqCDSrWi8

**Comment by Genato** [comment]
Same here.

This one trows error: https://www.youtube.com/watch?v=Zx_y2R5xJCQ
This one is playable: https://www.youtube.com/watch?v=taq-B4MkPdc&t=157s

**Comment by anxdpanic** [comment]
See, https://github.com/jdf76/plugin.video.youtube/releases/tag/6.8.3

**Comment by greatquux** [comment]
thanks so much for fixing it so quickly!

**Comment by sbstp** [comment]
Thanks, looks good.
