### ISSUE TITLE
this line is breaking on unicode strings

### ISSUE THREAD

**Issue by teamblubee** [jdf76/plugin.video.youtube#869]
https://github.com/jdf76/plugin.video.youtube/blob/374be55cf783438f64ca4f98dbefc42517bac171/resources/lib/youtube_plugin/kodion/abstract_provider.py#L247

I fixed this issue on my local machine but a recent update broke it again.
When you have the query as non ascii it will break. This happens when I try to search the plugin for strings not in ascii.

typically the errors look like this

```
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'\u6211'
                                            Traceback (most recent call last):
                                              File "/home/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 104, in navigate
                                                result = method(context, re_match)

```

The quickest fix is just to add this unicode encode to the strings before sending it to the query.

```
            query = query.encode('utf-8')
            self._data_cache.set('search_query', json.dumps({'query': quote(query)}))^M
```

Hopefully this is a easy fix.

**Comment by arthur-liberman** [comment]
Can confirm the above issue (russian input language), and the above change fixes the problem.
Thanks.

**Comment by anxdpanic** [comment]
Thanks for reporting, I missed this as development in now continued https://github.com/anxdpanic/plugin.video.youtube/ as mentioned in #871 

https://github.com/anxdpanic/plugin.video.youtube/releases/tag/6.x.x-dev contains the fix
