### ISSUE TITLE
Invalid URL 'http://': No host supplied

### ISSUE THREAD

**Issue by MikeJohnsonDev** [jdf76/plugin.video.youtube#870]
Hi,

I'm using Kodi 19 with 6.8.4-beta 2.

When I try to play https://www.youtube.com/watch?v=jb23b-zUkaU, I get the following error:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'requests.exceptions.InvalidURL'>
Error Contents: Invalid URL 'http://': No host supplied
Traceback (most recent call last):
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\default.py", line 15, in <module>
    runner.run(__provider__)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\runner.py", line 60, in run
    __RUNNER__.run(provider, context)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_runner.py", line 33, in run
    results = provider.navigate(context)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\abstract_provider.py", line 104, in navigate
    result = method(context, re_match)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\register_provider_path.py", line 19, in wrapper
    return func(*args, **kwargs)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 763, in on_play
    return yt_play.play_video(self, context)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\yt_play.py", line 50, in play_video
    video_streams = client.get_video_streams(context, video_id)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\client\youtube.py", line 100, in get_video_streams
    video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 506, in load_stream_infos
    return self._method_get_video_info(video_id, player_config, cookies)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 947, in _method_get_video_info
    cipher)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\video_info.py", line 1249, in generate_mpd
    url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\signature\cipher.py", line 32, in get_signature
    json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\function_cache.py", line 108, in get
    cached_data = partial_func()
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\signature\cipher.py", line 52, in _load_json_script
    result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
    File "C:\Users\Lounge\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'http://': No host supplied
-->End of Python script error report<-
```

**Comment by anxdpanic** [comment]
@MikeJohnsonDev I've moved the issue to this projects new repository, please see https://github.com/anxdpanic/plugin.video.youtube/issues/10 
The latest beta should hopefully resolve the issue.

**Comment by ypcyc** [comment]
```
021-01-26 20:43:40.853 T:140612565186304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Invalid URL u'http://': No host supplied
                                            Traceback (most recent call last):
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 105, in navigate
                                                result = method(context, re_match)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 911, in _method_get_video_info
                                                license_info.get('url'))
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1216, in generate_mpd
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/opt/Kodi18/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 52, in _load_json_script
                                                result = requests.get(url, headers=headers, verify=self._verify, allow_redirects=True)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request
                                                prep = self.prepare_request(req)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 462, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare
                                                self.prepare_url(url, params)
                                              File "/opt/Kodi18/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http://': No host supplied
                                            -->End of Python script error report<--
```
