### ISSUE TITLE
v6.8.3: No streams found

### ISSUE THREAD

**Issue by johanburati** [jdf76/plugin.video.youtube#880]
I am using the latest version of the plugin (**v6.8.10**) and getting the `No streams found` error from today:

```
021-06-16 15:08:46.840 T:140124641814272   ERROR: Traceback (most recent call last):
2021-06-16 15:08:46.840 T:140124641814272   ERROR:   File "/home/job/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
2021-06-16 15:08:46.840 T:140124641814272   ERROR:     video_streams = client.get_video_streams(context, video_id)
2021-06-16 15:08:46.840 T:140124641814272   ERROR:   File "/home/job/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
2021-06-16 15:08:46.840 T:140124641814272   ERROR:     video_streams = video_info.load_stream_infos(video_id)
2021-06-16 15:08:46.840 T:140124641814272   ERROR:   File "/home/job/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 515, in load_stream_infos
2021-06-16 15:08:46.840 T:140124641814272   ERROR:     return self._method_get_video_info(video_id)
2021-06-16 15:08:46.840 T:140124641814272   ERROR:   File "/home/job/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1032, in _method_get_video_info
2021-06-16 15:08:46.840 T:140124641814272   ERROR:     raise YouTubeException('No streams found')
2021-06-16 15:08:46.840 T:140124641814272   ERROR: YouTubeException: No streams found
2021-06-16 15:08:46.840 T:140124641814272   ERROR: [plugin.video.youtube] None
2021-06-16 15:08:46.850 T:140129436887744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=v27CEFE02Hs]
```

**Comment by jmh2002** [comment]
There is actually a different GitHub for the YouTube addon now.

Here is the thread for this issue and the post with the work around:

https://github.com/anxdpanic/plugin.video.youtube/issues/129#issuecomment-862014049
