### ISSUE TITLE
Plugin does not work (with API key) via search function, only with live streams

### ISSUE THREAD

**Issue by abcnorio** [jdf76/plugin.video.youtube#882]
OS:
Kodi Leia (libreelec 9.2.8, RPi) 18.9.0 from 2021-07-06
plugin version 6.8.15 as well as 6.8.16-alpha (same behavior)

I have the same problem on CoreElec Matrix (latest YT plugin)

Problem: plugin stopped working to play videos completely (either sent via webbrowser to kodi OR via plugin search function). Live streams directly chosen from the plugin DO work (if they can be selected because they are shown by the plugin), but nothing can be played via search function. Search function and preview of thumbs works too according with short infos about videos.

API is available AND was re-applied with success (ie. log-out with the plugin, log-in and confirm via google.com/device and login there to confirm).

Error is always the same on all devices. It worked without problems till maybe 1-2 weeks (did not use it last 2 weeks).

### START kodi.log
2021-08-11 11:20:40.569 T:1795158912   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning,
2021-08-11 11:21:14.932 T:1795158912   ERROR: Previous line repeats 5 times.
2021-08-11 11:21:14.932 T:1795158912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'function(c'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 34, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 124, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 767, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 104, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 536, in load_stream_infos
                                                return self._method_get_video_info(video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1092, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1052, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 31, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_javascript, self._javascript)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 75, in _load_javascript
                                                param = int(param)
                                            ValueError: invalid literal for int() with base 10: 'function(c'
                                            -->End of Python script error report<--
2021-08-11 11:21:15.331 T:1936707648   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=XnSTfwI9cPo]

### END kodi.log

What is the problem here?

best and thanks.

**Comment by kiorky** [comment]
confirmed

**Comment by kiorky** [comment]
see https://github.com/anxdpanic/plugin.video.youtube/issues/179

**Comment by abcnorio** [comment]
solved by https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v6.8.16 + confirmed.
